### ISSUE TITLE
Yaml file not loaded as OrderedDict

### ISSUE THREAD

**Issue by atantet** [wimglenn/oyaml#19]
The following code gives me a `dict`:

```
import oyaml as yaml
cfg = yaml.load("---\ncat: 1\ndog:\n\tdog1: 2\n\tdog2: 3")
type(cfg)
```

With these module versions:
oyaml                     0.9                      py37_0    conda-forge
pyyaml                    5.1.1            py37h516909a_0    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge

**Comment by wimglenn** [comment]
That's normal for Python-3.7+.  The stdlib dict is good enough for preserving order, so you can  just use a std dict.
