### ISSUE TITLE
Clearify the relation with pyyaml

### ISSUE THREAD

**Issue by cknoll** [wimglenn/oyaml#22]
The README.md or some other docs should make it more obvious whether this is a fork of https://pyyaml.org/wiki/PyYAML ([repo](https://github.com/yaml/pyyaml)) and in which aspects it differs from it. This seems relevant due to
- security <https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation>
- functionality <https://github.com/yaml/pyyaml/issues/252> which indicates that ordering is preserved in current pyyaml

**Comment by wimglenn** [comment]
1. This is not a fork of PyYAML, it's a monkeypatch. It does not address any security vulnerabilities - if you're deserializing untrusted input, you should use the `SafeLoader` in `oyaml` just the same as you should in `PyYAML`.
2. Previous versions didn't preserve ordering, oyaml would patch that. If the version of PyYAML installed preserves ordering then oyaml is unnecessary. In this case, the only aspect that differs would be the behavior for dumping `collections.OrderedDict` instances. `oyaml` will just represent them as normal maps, whereas `yaml` will either represent them as python objects (`yaml.dump`) or refuse to serialise them at all (`yaml.safe_dump`), raising a `RepresenterError`.
