### ISSUE TITLE
Not receiving an ordered dict

### ISSUE THREAD

**Issue by spaceKelan** [wimglenn/oyaml#27]
Hi @wimglenn,

thank you for your work! I am trying to read in attributes in a yaml file in its order, it looks like this
``` 
test:
  c: C
  b: B
  a: A
  d: D
```
and my python script like this
```
import oyaml as oyaml

with open(<absolute path to yaml file>) as f:
    data = oyaml.safe_load(f)
pprint(data["test"])
```
executing it with the installed python 3.8.10 results in this
```
{'a': 'A', 'b': 'B', 'c': 'C', 'd': 'D'}
```
and the debugger confirms it is a dict, not an OrderedDict.
I don't understand why it is not working, but I assume I do not use the module as intended.

I am looking forward to your help.

Sincerely,

Andy

**Comment by wimglenn** [comment]
@spaceKelan  

Two things: `oyaml` will only return an `OrderedDict` instance in Python versions where the standard dict is not order preserving. You will get a standard dict in Python 3.8.10.

It looks like you're using [`pprint`](https://docs.python.org/3/library/pprint.html#pprint.pprint). This function sorts dicts by default, so it just undoes the ordering. Either use a normal `print`, pass `sort_dicts=False` when calling `pprint`, or use [`pp`](https://docs.python.org/3/library/pprint.html#pprint.pp) instead which disables the dict sorting "feature".
