### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by tacerus** [wimglenn/oyaml#29]
Hi,

I am building a distribution package and notice the tests on the 1.0 release won't run with the new PyYAML anymore. Since there's a patch in master (d0195070d26bd982f1e4e604bded5510dd035cd7) for a while now, would it be possible to get a new release version tagged?

Cheers,
Georg

**Comment by wimglenn** [comment]
Ok, do you just need a tag (and the corresponding GitHub archive), and not an actual release to PyPI? As I understand it there is no change to library code, only the tests.

**Comment by tacerus** [comment]
Hi @wimglenn, that's correct, only the tag would do - I build off the Git sources directly and do not use PyPI.

**Comment by wimglenn** [comment]
https://github.com/wimglenn/oyaml/releases/tag/v1.1

**Comment by tacerus** [comment]
Awesome, thank you very much!
