### ISSUE TITLE
Missing latest version on PyPI

### ISSUE THREAD

**Issue by teddythinh** [wimglenn/oyaml#30]
Hi @wimglenn, I'm using pip to install the latest version of oyaml, as I could see on the oyaml PyPI page, the latest version is `1.0`, but when I check on the GitHub page, you have updated to the `1.1` version. Are there any differences between these two versions, I'm using the latest version of PyYAML `6.0.1`. Thank you.

**Comment by wimglenn** [comment]
See https://github.com/wimglenn/oyaml/issues/29 for context. 

There are no user-facing changes in this tag, only in the tests. Hence no release to PyPI, to avoid unnecessary dependency churn.

**Comment by teddythinh** [comment]
Thank you!
